"""
Django settings for cfehome project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from pymongo import MongoClient
from dotenv import load_dotenv
from mongoengine import connect
# Load environment variables from .env file
load_dotenv('.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# MongoDB Connection
CONNECTION_STRING = os.getenv('MONGO_DB_ATLAS_URI')
if not CONNECTION_STRING:
    raise ValueError("MONGO_DB_ATLAS_URI environment variable is not set")

# Connect to MongoDB using mongoengine
client = connect(host=CONNECTION_STRING)
DB_NAME = os.getenv('MONGO_DB_NAME')

if not DB_NAME:
    raise ValueError("MONGO_DB_NAME environment variable is not set")

DB = client[DB_NAME]

# PyMongo client for direct database access if needed
MONGO_CLIENT = MongoClient(CONNECTION_STRING)

KAFKA_DEVELOPMENT_SERVER = os.getenv('KAFKA_BROKERS_DEV', 'localhost:29092') # Default for local dev
KAFKA_PRODUCTION_SERVER = os.getenv('KAFKA_BROKERS_PROD', 'kafka:9092') # Example for Docker Compose

IS_PRODUCTION = os.getenv('IS_PRODUCTION', 'false').lower() == 'true' # Better boolean conversion

KAFKA_BOOTSTRAP_SERVERS = KAFKA_PRODUCTION_SERVER if IS_PRODUCTION else KAFKA_DEVELOPMENT_SERVER

KAFKA_PREDICTION_TOPIC = os.getenv('KAFKA_PREDICTION_TOPIC')
KAFKA_CONSUMER_GROUP_ID = os.getenv('KAFKA_CONSUMER_GROUP_ID')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oz7z@o)hciz(8fdc(=t^=87jptqh&#hptk4l2&qw$ls1m0hf!!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS_str = os.getenv('ALLOWED_HOSTS', 'prediction-service,localhost,127.0.0.1')
ALLOWED_HOSTS = ALLOWED_HOSTS_str.split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'prediction_price',
    'rest_framework',
    "corsheaders",
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cfehome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cfehome.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
CORS_ALLOW_ALL_ORIGINS = True
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis-service:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}